routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/download/{file}', function ($file='') {
    return response()->download(public_path('files/'.$file)); 
});
Route::get('zipFiles/{names}' , 'FileController@zipFile');

Route::group(['middleware' => ['auth:web,staff','prevent-back-history']], function() {
Route::group(['middleware' => ['permission:products|all']], function() {
    // Product Controller
    Route::resource('products' , 'ProductController');
    Route::get('ajaxProducts','ProductController@getAjaxProducts')->name('ajaxProducts');
    Route::get('deleteProduct/{id}','ProductController@deleteProduct');
    Route::post('updateProduct' , 'ProductController@update');
});

Route::group(['middleware' => ['permission:orders|all']], function() {
    // Order Controller
    Route::get('ajaxOrders/{year}/{month}','OrderController@getOrders');
    Route::get('orders' , 'OrderController@index');
    Route::get('addOrder' , 'OrderController@create');
    Route::post('addOrder' , 'OrderController@store')->name('addOrder');
    Route::get('editOrder/{id}','OrderController@edit')->name('editOrder');
    Route::post('updateOrder' , 'OrderController@update')->name('updateOrder');
    Route::get('deleteOrder/{id}','OrderController@delete');

    // Order Details and Modify Order
    Route::get('orderUpdate/{id}' , 'OrderController@updateOrder');
    Route::get('orderDetails/{id}' , 'OrderController@orderDetails');
    Route::get('deleteOrderItem/{id}/{order_item}' , 'OrderController@deleteOrderItem');
    Route::get('orderStatus/{id}/{status}' , 'OrderController@changeOrderStatus');
    Route::post('orderUserAddress' , 'OrderController@orderUserAddress');
    Route::post('orderChange' , 'OrderController@orderChange');
    Route::post('updateOrderItems', 'OrderController@updateOrderItems');

});

Route::group(['middleware' => ['permission:sales|all']], function() {
    // Sales Routes
    Route::get('ajaxSales/{year}/{month}','SalesController@getSales');
    Route::get('ajaxSalesItems/{year}/{month}','SalesController@getSalesItems');
    Route::get('ajaxSalesDate/{start}/{end}','SalesController@getSalesDate');
    Route::get('sales' , 'SalesController@index');
    Route::get('saleDetails/{date}' , 'SalesController@saleDetails');
    Route::get('saleItemsMonth' , 'SalesController@saleItemsMonth');
});

Route::group(['middleware' => ['permission:financials|all']], function() {
    //Financials Routes
    Route::get('financials' , 'FinancialController@financials');
    Route::get('ajaxFinancials/{year}/{month}' , 'FinancialController@getFinancials');
    Route::get('ajaxFinancialDates/{start}/{end}' , 'FinancialController@getFinancialDates');

    //Expenses Routes
    Route::get('expenses' , 'ExpenseController@index');
    Route::get('addExpense' , 'ExpenseController@create');
    Route::get('editExpense/{id}' , 'ExpenseController@edit')->name('expenses.edit');
    Route::post('addExpense' , 'ExpenseController@store');
    Route::post('editExpense' , 'ExpenseController@update');
    Route::get('deleteExpense/{id}' , 'ExpenseController@delete');
    Route::get('ajaxExpenses/{year}/{month}','ExpenseController@getExpenses');

    //Revenues Routes
    Route::get('revenues' , 'RevenueController@index');
    Route::get('addRevenue' , 'RevenueController@create');
    Route::get('editRevenue/{id}' , 'RevenueController@edit')->name('revenues.edit');
    Route::post('addRevenue' , 'RevenueController@store');
    Route::post('editRevenue' , 'RevenueController@update');
    Route::get('deleteRevenue/{id}' , 'RevenueController@delete');
    Route::get('ajaxRevenues/{year}/{month}','RevenueController@getRevenues');

});

Route::group(['middleware' => ['permission:files|all']], function() {
    // Files Routes
    Route::get('files' , 'FileController@index');
    Route::get('addFile' , 'FileController@create');
    Route::post('addFile' , 'FileController@store');
    Route::get('deleteFile/{id}' , 'FileController@delete');
});

Route::group(['middleware' => ['permission:testimonials|all']], function() {

    //Testimonial Routes
    Route::get('testimonials' , 'TestimonialController@index');
    Route::get('addTestimonial' , 'TestimonialController@create');
    Route::get('editTestimonial/{id}' , 'TestimonialController@edit')->name('testimonials.edit');
    Route::post('addTestimonial' , 'TestimonialController@store');
    Route::post('editTestimonial' , 'TestimonialController@update');
    Route::get('deleteTestimonial/{id}' , 'TestimonialController@delete');
    Route::get('ajaxTestimonials','TestimonialController@getTestimonials');
});


Route::group(['middleware' => ['permission:staff|all']], function() {
    //Staff Routes
    Route::get('staff' , 'StaffController@index')->name('staff');
    Route::get('addStaff' , 'StaffController@create');
    Route::get('editStaff/{id}' , 'StaffController@edit')->name('staff.edit');
    Route::post('addStaff' , 'StaffController@store');
    Route::post('editStaff' , 'StaffController@update');
    Route::get('deleteStaff/{id}' , 'StaffController@delete');
    Route::get('ajaxStaff','StaffController@getStaff');


    //Roles Routes
    Route::get('roles' , 'RolesController@index');
    Route::get('addRole' , 'RolesController@create');
    Route::get('editRole/{id}' , 'RolesController@edit')->name('roles.edit');
    Route::post('addRole' , 'RolesController@store');
    Route::post('editRole' , 'RolesController@update');
    Route::get('deleteRole/{id}' , 'RolesController@delete');
    Route::get('ajaxRoles','RolesController@getRoles');

    // Permission Route
    Route::get('permissions/{id}', 'RolesController@permission');
    Route::get('addPermission/{role}/{permission}', 'RolesController@addPermission');
    Route::get('removePermission/{role}/{permission}', 'RolesController@removePermission');

    // Client Routes
    Route::get('clients' , 'ClientController@index');
    Route::get('ajaxClients' , 'ClientController@getClients');
});


Route::group(['middleware' => ['permission:reminders|all']], function() {
    //Reminders Routes
    Route::get('reminders' , 'ReminderController@index');
    Route::get('addReminder' , 'ReminderController@create');
    Route::get('editReminder/{id}' , 'ReminderController@edit')->name('reminders.edit');
    Route::post('addReminder' , 'ReminderController@store');
    Route::post('editReminder' , 'ReminderController@update');
    Route::get('deleteReminder/{id}' , 'ReminderController@delete');
    Route::get('ajaxReminders','ReminderController@getReminders');

});

Route::group(['middleware' => ['permission:all|dashboard']], function() {
    Route::get('/', 'HomeController@index');
    Route::get('/home', 'HomeController@index')->name('home');
});

});


Auth::routes(['register' => false]);

Route::get('meme', 'Auth\RegisterController@showRegistrationForm');
Route::post('meme', 'Auth\RegisterController@register')->name('register');

Route::get('checkReminder', 'ReminderController@checkReminder');
Route::get('/logout', 'Auth\LoginController@logout');

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    protected $fillable = ['name', 'short_name' , 'price', 'block', 'image', 'unit', 'web', 'mob', 'adm'];
    public static function block($val){
        if($val == 0)
        return "Approve";
        else
        return "Block";
    }
}

app/Http/Controllers/Api/ProductController.php
<?php

namespace App\Http\Controllers\Api;

use App\Product;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class ProductController extends Controller
{
    public function products(){
        $products = Product::where(['block'  => 0])->get();
        return response()->json($products, 200);
    }

    public function productsWeb(){
        $products = Product::where(['block'  => 0])->where(['web'  => 1])->get();
        return response()->json($products, 200);
    }

    public function productsMob(){
        $products = Product::where(['block'  => 0])->where(['mob'  => 1])->get();
        return response()->json($products, 200);
    }

    public function productsAdm(){
        $products = Product::where(['block'  => 0])->where(['adm'  => 1])->get();
        return response()->json($products, 200);
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Product;
use App\Image;
use File;
use DataTables;
use Validator;
use Illuminate\Http\Request;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
    {
        // $this->middleware('auth:staff');
    }
        
     public function index(){
         return view('products.products');
     }
    
     public function getAjaxProducts()
    {
        $products = Product::select('id', 'name', 'short_name', 'block', 'image', 'price', 'unit' , 'created_at')
        ->get();

        foreach($products as $product){
            $product->block = Product::block($product->block);
        }

        return DataTables::of($products)
        ->addColumn('action', function ($id) {
            return '<a href="'. route("products.edit" , $id->id) .'" class="text-danger"><i class="fa fa-edit"></i></a>
            <a class="text-danger" onClick="delete_click('.$id->id.')" ><i class="fa fa-trash"></i></button>'; 
        })
        ->editColumn('image', function ($product) { 
            return '<img src='.$product->image.' border="0" width="40" class="img-rounded" align="center" />'; 
         })
         ->rawColumns(['image', 'action'])
        ->make(true);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('products.addProduct');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [ 
            'name' => 'required|max:50', 
            'short_name' => 'regex:/^[\pL\s\.]+$/u|max:20', 
            'price' => 'required|digits_between:1,6',
            'image' => 'required',
            'unit' => 'required'
        ]);

        if ($validator->fails()) { 
            return redirect()->back()->withErrors($validator)->withInput();
        }

        $product = Product::create([
            'name' => $request->name , 
            'short_name' => $request->short_name , 
            'price' => $request->price , 
            'block' => $request->block , 
            'unit' => $request->unit ,
            'image' => '' 
        ]);
        $product->save();

        $imageUrl = "";

        if($request->hasfile('image')){
            $files = $request->file('image');
            for($i=0 ; $i<count($files) ; $i++){
                $img = "";
                $file = $files[$i];
                $filename = time().$i.'.'.$file->getClientOriginalExtension();
                $destinationPath = public_path('/images');
                $file->move($destinationPath, $filename);    
                $img = asset("public/images/".$filename);
                $image = new Image();
                $image->name = $filename;
                $image->imageUrl = $img;
                $image->product_id = $product->id;
                $image->save();
    
                if($i == 0){
                    $imageUrl = asset("public/images/".$filename);
                }
            }
        }

        $productUpdate = Product::where(['id' => $product->id])->first();
        if($request->mob){
            $productUpdate->mob = 1;
        }else{
            $productUpdate->mob = 0;
        }
        if($request->web){
            $productUpdate->web = 1;
        }else{
            $productUpdate->web = 0;
        }
        if($request->adm){
            $productUpdate->adm = 1;
        }else{
            $productUpdate->adm = 0;            
        }        
        $productUpdate->image = $imageUrl;
        $productUpdate->save();

        return redirect('products')->with('message', 'Product Added Successfully');;
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function show(Product $product)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $product = Product::where(['id' => $id])->first();
        return view('products.editProduct' , compact('product'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Product $product)
    {
        $validator = Validator::make($request->all(), [ 
            'name' => 'required|max:50', 
            'short_name' => 'regex:/^[\pL\s\.]+$/u|max:20', 
            'price' => 'required|digits_between:1,8',
            'unit' => 'required'
            ]);

        if ($validator->fails()) { 
            return redirect()->back()->withErrors($validator);
        }

        $product = Product::where(['id' => $request->id])->first();

        $product->name = $request->name;
        $product->short_name = $request->short_name;
        $product->price = $request->price;
        $product->block = $request->block;
        $product->unit = $request->unit;
        if($request->mob){
            $product->mob = 1;
        }else{
            $product->mob = 0;
        }
        if($request->web){
            $product->web = 1;
        }else{
            $product->web = 0;
        }
        if($request->adm){
            $product->adm = 1;
        }else{
            $product->adm = 0;            
        }
        $imageUrl = "";

        if($request->hasfile('image')){
            // Removing previous Images
            $images = Image::where(['product_id' => $request->id])->get();
            foreach($images as $image){
                $destinationPath = public_path('/images')."/".$image->name;
                if(File::exists($destinationPath)) {
                    File::delete($destinationPath);            
                }
                $image->delete();
            }            
            
            $files = $request->file('image');
            for($i=0 ; $i<count($files) ; $i++){
                $img = "";
                $file = $files[$i];
                $filename = time().$i.'.'.$file->getClientOriginalExtension();
                $destinationPath = public_path('/images');
                $file->move($destinationPath, $filename);    
                $img = asset("public/images/".$filename);
                $image = new Image();
                $image->name = $filename;
                $image->imageUrl = $img;
                $image->product_id = $product->id;
                $image->save();
    
                if($i == 0){
                    $imageUrl = asset("public/images/".$filename);
                }
            }

            $product->image = $imageUrl;
        }

        $product->save();

        return redirect()->back()->with('message', 'Product Updated Successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function destroy(Product $product)
    {
        
    }

    public function deleteProduct($id){
        $images = Image::where(['product_id' => $id])->get();
        foreach($images as $image){
            $destinationPath = public_path('/images')."/".$image->name;
            if(File::exists($destinationPath)) {
                File::delete($destinationPath);            
            }
            $image->delete();
        }

        Product::where(['id' => $id])->delete();
        
        return redirect()->back()->with('message', 'Product Deleted Successfully');;
    }
}

resources/views/products/addProduct.blade.php
@extends('layouts.main')

@section('title' , 'Add Product')

@section('styles')
    <style>
      .add-product-form{
        margin:0px 20%;
      }
      .error{
        color:red;
        font-size:1rem;
      }
      .submit-btn{
        margin-top:20px; 
        margin-bottom:20px; 
      }
      #grouped_items{
        display:none;
      }
      @media screen and (max-width: 600px) {
        .add-product-form{
          margin:0px 5%;
        }
      }
    </style>
@endsection

@section('content')
<div class="container-fluid">
<form  class="add-product-form" enctype="multipart/form-data"
 action="{{route('products.store')}}" id="add_product" method="post">
@csrf

  <div class="form-group">
    <label for="productInput">Product Name</label>
    <input type="text" name="name" class="form-control" id="productInput" value="{{old('name')}}" aria-describedby="productNameHelp" placeholder="Enter product name">
    @if($errors->has('name'))
    <small id="productNameHelp" class="form-text error">{{ $errors->first('name') }}</small>
    @endif
  </div>

  <div class="form-group">
    <label for="productShortInput">Product Short Name</label>
    <input type="text" name="short_name" class="form-control" id="productShortInput" value="{{old('short_name')}}" aria-describedby="productShortNameHelp" placeholder="Enter product short name">
    @if($errors->has('short_name'))
    <small id="productShortNameHelp" class="form-text error">{{ $errors->first('short_name') }}</small>
    @endif
  </div>


  <div class="form-group">
    <label for="productPrice">Product Price</label>
    <input type="text" name="price" class="form-control" {{old('price')}} id="productPrice" aria-describedby="productPriceHelp" placeholder="Enter product price">
    @if($errors->has('price'))
    <small id="productPriceHelp" class="form-text error">{{ $errors->first('price') }}</small>
    @endif
  </div>

  <div class="form-group">
    <label for="productPrice">Product Unit</label>
    <select name="unit" class="form-control" id="">
      <option value="Kg">Kg</option>
      <option value="Dozen">Dozen</option>
    </select>
    @if($errors->has('unit'))
    <small id="productUnitHelp" class="form-text error">{{ $errors->first('unit') }}</small>
    @endif
  </div>

  <div class="form-group">
    <div class="custom-control custom-radio custom-control-inline">
        <input type="radio" class="custom-control-input" id="customRadio2" value="0" name="block" checked>
        <label class="custom-control-label" for="customRadio2">Approve</label>
    </div>

    <div class="custom-control custom-radio custom-control-inline">
        <input type="radio" class="custom-control-input" id="customRadio1" value="1" name="block">
        <label class="custom-control-label" for="customRadio1">Block</label>
      </div>
  </div>

  <label for="">Visible on</label>
  <div class="form-group">
    <div class="custom-control custom-checkbox custom-control-inline">
        <input type="checkbox" class="custom-control-input" id="web" name="web">
        <label class="custom-control-label" for="web">Web</label>
    </div>

    <div class="custom-control custom-checkbox custom-control-inline">
        <input type="checkbox" class="custom-control-input" id="mob" name="mob">
        <label class="custom-control-label" for="mob">Mobile</label>
      </div>

    <div class="custom-control custom-checkbox custom-control-inline">
      <input type="checkbox" class="custom-control-input" id="adm" name="adm">
      <label class="custom-control-label" for="adm">Admin</label>
    </div>
  </div>

  <div class="form-group">
        <input type="file" name="image[]"  multiple>
        @if($errors->has('image'))
          <small id="productImageHelp" class="form-text error">{{ $errors->first('image') }}</small>
        @endif
  </div>    

  <button id="submit" class="btn btn-primary submit-btn">Submit</button>
</form>

</div>
@endsection

@section('scripts')
@endsection

resources/views/products/editProduct.blade.php
@extends('layouts.main')

@section('title' , 'Edit Product')

@section('styles')
    <style>
      .edit-product-form{
        margin:0px 20%;
      }
    .error{
      color:red;
      font-size:1rem;
    }
    .submit-btn{
        margin-top:20px; 
        margin-bottom:20px; 
      }
      #grouped_items{
        display:none;
      }

      @media screen and (max-width: 600px) {
        .edit-product-form{
          margin:0px 5%;
        }
      }

    .custom-control-input:checked~.custom-control-label::before {
        color: #fff;
        border-color: #e74a3b;
        background-color: #e74a3b;
    }
    </style>
@endsection

@section('content')
<div class="container-fluid">

<form  class="edit-product-form" enctype="multipart/form-data"
 action="{{url('updateProduct')}}" id="edit_product" method="post">

 @if(session()->has('message'))
    <div id="alert" class="alert alert-success">
        {{ session()->get('message') }}
    </div>
@endif


@csrf
  <input type="hidden" name="id" value="{{$product->id}}">

  <div class="form-group">
    <label for="productInput">Product Name</label>
    <input type="text" name="name" class="form-control" value="{{$product->name}}" id="productInput" aria-describedby="productNameHelp" placeholder="Enter product name">
    @if($errors->has('name'))
    <small id="productNameHelp" class="form-text error">{{ $errors->first('name') }}</small>
    @endif
  </div>

  <div class="form-group">
    <label for="productShortInput">Product Short Name</label>
    <input type="text" name="short_name" class="form-control" value="{{$product->short_name}}" id="productShortInput" aria-describedby="productShortNameHelp" placeholder="Enter product short name">
    @if($errors->has('short_name'))
    <small id="productShortNameHelp" class="form-text error">{{ $errors->first('short_name') }}</small>
    @endif
  </div>

  <div class="form-group">
    <label for="productPrice">Product Price</label>
    <input type="text" name="price" class="form-control" value="{{$product->price}}" id="productPrice" aria-describedby="productPriceHelp" placeholder="Enter product price">
    @if($errors->has('price'))
    <small id="productPriceHelp" class="form-text error">{{ $errors->first('price') }}</small>
    @endif
  </div>

  <div class="form-group">
    <label for="productPrice">Product Unit</label>
    <select name="unit" class="form-control" id="">
      <option @if($product->unit == "Kg") selected @endif value="Kg">Kg</option>
      <option @if($product->unit == "Dozen") selected @endif value="Dozen">Dozen</option>
    </select>
    @if($errors->has('unit'))
    <small id="productUnitHelp" class="form-text error">{{ $errors->first('unit') }}</small>
    @endif
  </div>

  <div class="form-group">
    <div class="custom-control custom-radio custom-control-inline">
        <input type="radio" class="custom-control-input" id="approve" value="0" name="block" @if($product->block == 0) checked @endif>
        <label class="custom-control-label" for="approve">Approve</label>
    </div>

    <div class="custom-control custom-radio custom-control-inline">
        <input type="radio" class="custom-control-input" id="block" value="1" name="block" @if($product->block == 1) checked @endif>
        <label class="custom-control-label" for="block">Block</label>
      </div>
  </div>

  <label for="">Visible on</label>
  <div class="form-group">
    <div class="custom-control custom-checkbox custom-control-inline">
        <input type="checkbox" class="custom-control-input" id="web" name="web" @if($product->web == 1) checked @endif>
        <label class="custom-control-label" for="web">Web</label>
    </div>

    <div class="custom-control custom-checkbox custom-control-inline">
        <input type="checkbox" class="custom-control-input" id="mob" name="mob" @if($product->mob == 1) checked @endif>
        <label class="custom-control-label" for="mob">Mobile</label>
      </div>

    <div class="custom-control custom-checkbox custom-control-inline">
      <input type="checkbox" class="custom-control-input" id="adm" name="adm" @if($product->adm == 1) checked @endif>
      <label class="custom-control-label" for="adm">Admin</label>
    </div>
  </div>

  <div class="form-group">
        <input type="file" name="image[]" multiple>
        @if($errors->has('image'))
          <small id="productImageHelp" class="form-text error">{{ $errors->first('image') }}</small>
        @endif
  </div>    


  <button id="submit" class="btn submit-btn btn-danger">Submit</button>
</form>

</div>
@endsection
@section('scripts')
<script>
     $("#alert").fadeTo(2000, 500).slideUp(500, function(){
       $("#alert").slideUp(600);
       });

    </script>
@endsection

resources/views/products/products.blade.php
@extends('layouts.main')

@section('title' , 'Products')

@section('styles')
    <link href="{{asset('public/vendor/datatables/dataTables.bootstrap4.min.css')}}" rel="stylesheet">
    <style>
      .error{
        color:red;
        font-size:1rem;
      }
      .small-h3{
        font-size:18px;
        font-weight:bold;
      }
      #toggle_event_editing{
        background:white !important;
      }

    </style>
@endsection

@section('content')
<div class="container-fluid">

@if(session()->has('message'))
    <div id="alert" class="alert alert-success">
        {{ session()->get('message') }}
    </div>
@endif

@if(session()->has('errorProducts'))
    <div id="alert" class="alert alert-danger">
        {{ session()->get('errorProducts') }}
    </div>
@endif
      <!-- Page Heading -->
      <h1 class="h3 mb-2 text-gray-800">Products </h1>
          <p class="mb-4">You can Add , Edit and Delete Products from there. <span class="float-right"><span><i class="fa fa-edit text-danger"></i></span> for Update <span><i class="fa fa-trash text-danger"></i></span> for Delete </span></p>
          <!-- DataTales Example -->
          <div class="mt-5 card shadow mb-4">
            <div class="card-header py-3">
              <h6 class="m-0 font-weight-bold text-danger">Products 
                <span class="float-right">
                  <a href="{{url('products/create')}}" title="Add Product"><button class="btn btn-sm btn-danger">Add Product</button></a>
                </span>
               </h6>
            </div>
            <div class="card-body">
              <div class="table-responsive">
                <table class="table table-bordered" id="productTable" width="100%" cellspacing="0">
                  <thead>
                    <tr>
                      <th>Id</th>
                      <th>Image</th>
                      <th>Name</th>
                      <th>S Name</th>
                      <th>Price</th>
                      <th>Unit</th>
                      <th>Block</th>
                      <th>Action</th>
                    </tr>
                  </thead>
                  <tfoot>
                    <tr>
                        <th>Id</th>
                        <th>Image</th>
                        <th>Name</th>
                        <th>S Name</th>
                        <th>Price</th>
                        <th>Unit</th>
                        <th>Block</th>
                        <th>Action</th>
                    </tr>
                  </tfoot>
                </table>
              </div>
            </div>
          </div>

        </div>
        <!-- /.container-fluid -->




          <!-- Logout Modal-->
  <div class="modal fade" id="deleteProductModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Are you sure to delete?</h5>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body">Select <span class="error">"Delete"</span> below if you are ready to delete the product.</div>
        <div class="modal-footer">
          <button class="btn btn-success" type="button" data-dismiss="modal">Cancel</button>
          <a class="btn btn-danger" id="deleteModel" href="#">Delete</a>
        </div>
      </div>
    </div>
  </div>



@endsection

@section('scripts')
  <!-- Page level plugins -->
  <script src="{{asset('public/vendor/datatables/jquery.dataTables.min.js')}}"></script>
  <script src="{{asset('public/vendor/datatables/dataTables.bootstrap4.min.js')}}"></script>

  <!-- Page level custom scripts -->
  <script src="{{asset('public/js/demo/datatables-demo.js')}}"></script>

  <script>
     $("#alert").fadeTo(2000, 500).slideUp(500, function(){
       $("#alert").slideUp(600);
       });

       function delete_click(clicked_id){
          $('#deleteModel').attr("href","{{url('deleteProduct')}}/"+clicked_id)
          $('#deleteProductModal').modal('show');
        }

        $(document).ready(function(){
            $('#productTable').DataTable({
              "processing":true,
              "serverside":true,
              "ajax":"{{route('ajaxProducts')}}",
              "columns":[
                {"data" : "id"},
                {"data" : "image"},
                {"data" : "name"},
                {"data" : "short_name"},
                {"data" : "price"},
                {"data" : "unit"},
                {"data" : "block"},
                {"data" : "action"}
              ]
            });
        });
  </script>
@endsection